
# -*- coding: utf-8 -*-

__title__ = "Select inner edges from face"
__doc__ = ""
__url__ = "https://forum.freecad.org/viewtopic.php?t=98065"


print()
print("<<< Macro selecting inner edges from face >>>")

def getEdges(face):
    innerEdges = []
    outerPoints = []

    for vertex in face.OuterWire.Vertexes:
        outerPoints.append(vertex.Point)

    for edge in face.Edges:
        for vertex in edge.Vertexes:
            for point in outerPoints:
                if Path.Geom.pointsCoincide(point, vertex.Point):
                    break
            else:
                if edge not in innerEdges:
                    innerEdges.append(edge)
    return innerEdges

def getEdgesIndexFromBody(body, innerEdges):
    indexList = set()
    for innerEdge in innerEdges:
        pI1 = innerEdge.Vertexes[0].Point
        pI2 = innerEdge.Vertexes[-1].Point
        for index, bodyEdge in enumerate(body.Shape.Edges):
            if round(innerEdge.Length, 1) != round(bodyEdge.Length, 1):
                continue
            pB1 = bodyEdge.Vertexes[0].Point
            pB2 = bodyEdge.Vertexes[-1].Point
            if (
                (Path.Geom.pointsCoincide(pI1, pB1) and Path.Geom.pointsCoincide(pI2, pB2))
             or (Path.Geom.pointsCoincide(pI1, pB2) and Path.Geom.pointsCoincide(pI2, pB1))
            ):
                indexList.add(index)
                break
    return indexList

def main(selExList):
    for selEx in selExList:
        objSel = selEx.Object
        sub = selEx.SubElementNames[0]
        body = objSel.getSubObject(sub, 1)
        for face in selEx.SubObjects:
            if face.Faces:
                innerEdges = getEdges(face)
                innerEdgesIndex = getEdgesIndexFromBody(body, innerEdges)

                print(f"    Found {len(innerEdgesIndex)} edges on selected face")

                Gui.Selection.clearSelection()
                for index in innerEdgesIndex:
                    Gui.Selection.addSelection(body, str("Edge" + str(index + 1)))


selExList = FreeCADGui.Selection.getSelectionEx("", 0)

if selExList:
    main(selExList)
else:
    print(f'    Nothing selected')
