# Macro to move down selected objects in group

import FreeCAD
import FreeCADGui

print()
print("<<< Move down >>>")


def moveDown(selections):

    groupInList = selections[0].InList
    if len(groupInList) == 0:
        return "    Selection incorrect"

    groupObj = groupInList[0]
    for sel in selections:
        if sel not in groupObj.Group:
            return "    Selection incorrect"

    operations = [op.Label for op in selections]
    print(f"    {", ".join(map(str, operations))}")

    indexList = []
    for sel in selections:
        indexList.append(groupObj.Group.index(sel))

    newList = list(groupObj.Group)

    limitIndex = 0
    for index in sorted(indexList, reverse=True):
        limitIndex += 1
        if index < len(groupObj.Group) - limitIndex:
            sel = groupObj.Group[index]
            newList.pop(index)
            newList.insert(index+1, sel)

    groupObj.removeObjects(groupObj.Group)
    groupObj.addObjects(newList)

    doc.recompute()


doc = FreeCAD.ActiveDocument
selections = FreeCADGui.Selection.getSelection()
output = moveDown(selections)
if output:
    print(output)
